name: Serverless Deploy

on:
  push:
    branches:
    # change to "main" to actually deploy
    - main_

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install packages
      run: npm i
    
    - name: Run tests
      run: npm test
    
    - name: Copy env
      run: 'echo -e "${{secrets.ENV}}" > .env.production'
    
    - name: Serverless AWS authentication
      run: npx sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY }} --secret ${{ secrets.AWS_SECRET_KEY }}
    
    - name: Deploy Lambda functions
      run: NODE_ENV=production npx sls deploy